del /s /q *.o
del /s /q *.ppu
del /s /q server_console\*.exe
del /s /q server_gui\*.exe
del /s /q password_generator\*.exe
del /s /q *.obj
del /s /q server_console\backup\*.*
del /s /q gui\backup\*.*
del /s /q lib\ftp\backup\*.*